# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform mbleven comparison on two strings
#'
#' This is an Rcpp implementation of the mbleven algorithm. It takes two
#' strings as input and returns 0, 1, or 2 when the edit distance of the
#' strings are 0, 1, or 2 repsecitvely. If the edit distance if over three
#' edits, the algoirthm will return -1.
#'
#' @param str1 A character(1) vector.
#' @param str2 A character(1) vector.
#' @export
#' @examples
#' mbleven_compare('aaa', 'aaa')
#' mbleven_compare('aaa', 'abb')
#' mbleven_compare('aaa', 'bbb')
mbleven_compare <- function(str1, str2) {
    .Call(`_Rmbleven_mbleven_compare`, str1, str2)
}

